apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .values.namespace.name}}
spec:
  replicas: {{.values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{.values.image.repository}}
        name: techtrends
        resources:{{.values.resources}}
        container port: {{.values.containerPort}}
        livenessProbe:{{.values.livenessProbe}}
        readinessProbe:{{.values.readinessProbe}}
status: {}