apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: techtrends
        resources:{{.Values.resources}}
        container port: {{.Values.containerPort}}
        livenessProbe:{{.Values.livenessProbe}}
        readinessProbe:{{.Values.readinessProbe}}
status: {}