containerPort: 3111
image: 
  pullPolicy: IfNotePresent
  repository: gpcmax/techtrends
  tag: latest
livenessProbe: 
  httpGet: 
    path: /healthz
    port: 3111
namespace: 
  name: techtrends
readinessProbe: 
  httpGet: 
    path: /healthz
    port: 3111
replicaCount: 1
resources: 
  limits: 
    CPU: 500m
    memory: 128Mi
  requests: 
    CPU: 250m
    memory: 64Mi
service: 
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP