image: 
  pullPolicy: IfNotePresent
  repository: gpcmax/techtrends
  tag: latest
livenessProbe: 
  path: /healthz
  port: 3111
namespace: 
  name: sandbox
ports: 
  containerPort: 3111
readinessProbe:
  path: /healthz
  port: 3111
replicaCount: 1
resources: 
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests:
    memory: "64Mi"
    cpu: "250m"
service: 
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP